version: '3'
name: readtweets

services:
  web:
    image: nginx:1.23.2
    ports:
      - "8080:80"
    volumes:
      - .:/opt/code
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/opt/code
